### ISSUE TITLE
add placeholder heights

### ISSUE THREAD

**Issue by nelsonpecora** [nymag/clay-kiln#27]
Allow schema to set different placeholder heights, e.g.

``` yaml
foo:
  _placeholder: This is placeholder text

# could become...

foo:
  _placeholder:
    text: This is placeholder text
    height: 800

# or even...

foo:
  _label: This is label (and placeholder) text
  _placeholder:
    height: 800
```

This would change it from the current behavior (parsing the schema and trying to set height based on what behaviors a field has). The default height would remain **300px**.
