### ISSUE TITLE
placeholders when multiple fields are empty

### ISSUE THREAD

**Issue by yoshokatana** [nymag/clay-kiln#490]
Right now, a placeholder for a group of fields can specify which field to check, e.g.

```yaml
_groups:
  group1:
    fields:
      - field1
      - field2
    _placeholder:
      ifEmpty: field1
```

We should allow people to specify more than one field in `ifEmpty`, since there are frequently fields that should display placeholders if both need data (for example, the url _and_ text of a link).

Specifying these options in an array doesn't allow us to define which logical operator we want, and some larger config object is burdensome, so I propose we use a simple, case-insensitive logical string:

```yaml
ifEmpty: field1 and field2
ifEmpty: field1 AND field2
# would display if both field1 and field2 are empty

ifEmpty: field1 or field2
ifEmpty: field1 OR field2
# would display if either field1 or field2 are empty
```

As a special _one more thing_, I'd like to also add support for my favorite logical operator, XOR:

```yaml
ifEmpty: field1 xor field2
ifEmpty: field1 XOR field2
# would display if only field1 or field2 are empty
```
