### ISSUE TITLE
Limit Component List Include To Specific Sites

### ISSUE THREAD

**Issue by jonwinton** [nymag/clay-kiln#492]
Some components in articles don't need to be used across all sites, how can we localize them to only specific sites? Example: rating component is used only on Grub.

**Comment by yoshokatana** [comment]
Throwing some ideas out there:

```yaml
pageHeader:
  _componentList:
    include:
      - simple-header (not:thecut, not:vulture)
      - top-stories
      - early-often (di)
```

**GOOD:** Quick to write, makes sense in context, easy include/exclude filtering

**BAD:** Custom syntax

```yaml
pageHeader:
  _componentList:
    include:
      - 
        name: simple-header
        sites:
          - di
          - press
          - selectall
          - scienceofus
          - betamale
          # not thecut, vulture
      - top-stories
      - 
        name: early-often
        sites:
          - di
```

**GOOD:** No custom syntax

**BAD:** Verbose, no good way to exclude sites
