### ISSUE TITLE
magic-button should allow for MORE magic!

### ISSUE THREAD

**Issue by yoshokatana** [nymag/clay-kiln#493]
Idea: Sometimes we want to do multiple things when you press a magic button, e.g. two api calls.

We should create a new argument to `magic-button` called `moreMagic`, in which you can pass an array of objects that match the normal arguments to `magic-button` (effectively making it recursable).

Here's an example where we grab lede data's image, then get the caption from mediaplay:

```yaml
fn: magic-button
component: lede
transform: getComponentInstance
url: $SITE_PREFIX
property: imgUrl
moreMagic:
  -
    transform: mediaplayUrl
    url: image-server.url/images/
    property: caption
```
