### ISSUE TITLE
site-specific selector

### ISSUE THREAD

**Issue by yoshokatana** [nymag/clay-kiln#523]
```yaml
fn: site-specific-selector
sites:
  -
    url: grubstreet.com # regex
    options:
      - foo
      - bar # string array, like radio/select behavior
```

* displays as a `<select>` element, using the options for the specific site
* site is determined by a naive regex match of the url
