### ISSUE TITLE
component instance names

### ISSUE THREAD

**Issue by nelsonpecora** [nymag/clay-kiln#525]
In certain situations, it's useful for component instances to have some kind of human readable name that can be displayed (in lists, when searching for / adding already-created instances, etc). We should figure out a standardized way to do this for all components.

**Comment by yoshokatana** [comment]
Idea: similar to `_description`, a property in the component schema that specified what field (fields?) should be used for the "name", e.g.

```yaml
_name: adDescription

adDescription:
  _label: Ad Description
  _has: text
```

That would display whatever data is in the `adDescription` field as the instance's "name"

**Comment by yoshokatana** [comment]
Idea: similar to placeholders, make the name a string that can interpolate fields, e.g.

```yaml
_name: Ad - ${adDescription}

adDescription:
  _label: Ad Description
  _has: text
```

This would make things like having icons (for flex logic) and stuff in the name work, as well as using data from potentially _multiple_ fields
