### ISSUE TITLE
A field cannot be both rich text and be labeled

### ISSUE THREAD

**Issue by cperryk** [nymag/clay-kiln#709]
The settings view will not load for any component with a field that has both rich text and a label. For example:
```
title:
  _display: settings
  _label: Foo
  _has:
   - label
    -
      fn: wysiwyg
      enableKeyboardExtras: true
      styled: false
      buttons:
        - bold
        - italic
        - strikethrough
        - anchor
```

The gear icon will still appear on the component, but clicking it will have no effect. An error is not logged.
