### ISSUE TITLE
placeholder decorator: point to field

### ISSUE THREAD

**Issue by nelsonpecora** [nymag/clay-kiln#72]
If a group has a placeholder, it should be able to point to a specific field to check. E.g.

``` yaml
_groups:
  headlines:
    fields:
      - primaryHeadline
      - teaser
    _placeholder:
      height: 40px
      text: Article Headline
      ifEmpty: primaryHeadline # check the primaryHeadline field
    _display: overlay
```

It should:
- check to make sure that field exists (if not, error out)
- run `hasPlaceholder()` and `addPlaceholder()` using data from that specific field
